### PR TITLE
use semver with auto increment in label and fixed patch version

### LINKED ISSUE #49: Adopt new versioning strategy
Uses a fixed patch number and moves the autoincrement into the label; the release branch is the next milestone, for which the label in the version number will be dropped.

### PR DESCRIPTION
**Pull request by JorritSalverda**
fixes #49

### CODE REVIEW

**Comment by andrei-pavel** [comment]
Excuse me if this is a bit offtopic, is there a reason for Helm files being placed in the `estafette-gke-preemptible-killer` directory?

If I now do `git clone` and `go build`, it fails because it tries to place the binary where the directory now lies.
```
go build: build output "estafette-gke-preemptible-killer" already exists and is a directory
```

Could it be renamed to `helm` or back to `chart` or something else?

**Comment by andrei-pavel** [comment]
Same for other estafette applications, how do you compile? Do you always use `go build -o something`? Or do you have another build system?

**Comment by JorritSalverda** [comment]
I didn't realise since my Visual Studio Code IDE with plugins compile go code and on the command line I use `go test ./...`. I only let our CI/CD build the actual code. This directory is the default created when running `helm create ...`. I'll have a look what Helm suggests for this and see if we can equalise this across all applications that now have an official Helm chart.

**Comment by JorritSalverda** [comment]
I move the charts into the `helm` subdir and updated the `extensions/helm` image to by default assume it's in that directory.

**Pull request merged**
