### PR TITLE
Add permissions for nodes and pods to allow deletion

### LINKED ISSUE #52: Incomplete Documentation
After the changes to the newer Helm repo, when I install fresh it always gives a 403 error when following the readme file.

Pre private helm repo there used to be a flag to show where the Google Service Account JSON Key was this seems to be no more as a result HTTP 403 Forbidden is being received from the Kubernetes API.

### PR DESCRIPTION
**Pull request by phroggyy**
Hoping I didn't miss anything. This seems to work for our configuration

Resolves #52

### CODE REVIEW

**Comment by etiennetremel** [comment]
Thanks @phroggyy

**Comment by cagataygurturk** [comment]
Why does this app need access to secrets and events?

**Comment by etiennetremel** [comment]
Haven't seen that.. I think that's a mistake introduced by this PR https://github.com/estafette/estafette-gke-preemptible-killer/pull/50
It differs from the one in defined in the [manifests directory](https://github.com/estafette/estafette-gke-preemptible-killer/blob/master/manifests/rbac.yaml).
@JorritSalverda could you confirm the file is wrong in the helm chart? Also, it seems that the Merge pull request is disabled, could you review the status check? I'm happy to help fixing the Helm configuration.

**Comment by phroggyy** [comment]
@cagataygurturk @etiennetremel I propose we deal with removing those permissions in a separate PR, just to keep the commits and PRs targeted properly.

I've opened up a new issue to resolve that, and also opened up for a further point of discussion: https://github.com/estafette/estafette-gke-preemptible-killer/issues/55

**Comment by JorritSalverda** [comment]
@phroggyy and @etiennetremel it seems indeed the `ClusterRole` in the helm chart is incorrect; i'll fix it and create a new release for it.

**Comment by JorritSalverda** [comment]
Closing this in favour of https://github.com/estafette/estafette-gke-preemptible-killer/pull/57. I do value your contribution a lot, but we don't automatically build PRs from forks yet so it misses build status. I'll see if I can list you as a contributor in the release notes.

**Comment by phroggyy** [comment]
Thanks @JorritSalverda – I didn't realise they were out of sync until it was pointed out, so your MR is rightly more correct 👍

**Pull request closed without merging**
