### PR TITLE
Switch to the official Kubernetes Go client

### LINKED ISSUE #85: Switch to the official Kubernetes client
The Kubernetes client used in the application is not maintained anymore: https://github.com/ericchiang/k8s

### PR DESCRIPTION
**Pull request by cagataygurturk**
Switches to the official Kubernetes Go client.

Missing pieces:

- [ ] Drain nodes

Fixes #85

### CODE REVIEW

**Comment by kinghrothgar** [comment]
Would it be possible to also solve this issue during this re-write? https://github.com/estafette/estafette-gke-preemptible-killer/issues/22

**Comment by nemmyam** [comment]
Hi, Any chance this important PR will be merged soon?
Can I help in any way?

**Comment by cagataygurturk** [comment]
Hi, I will not be able to continue with this PR anymore due to time constraints. There shouldn't be a lot of pending work if anyone is willing to pick up.

**Comment by nemmyam** [comment]
Looks like #90 has already done it and just waiting for an approve from you :)

**Pull request closed without merging**
