### PR TITLE
[📦 NEW] blacklist & whitelist hours

### PR DESCRIPTION
**Pull request by andrei-pavel**
Have you only just taken up preemptible nodes, but your hosted services are not yet fully adapted to re-establish connections after a node gets killed?

Have you had enough of being interrupted from lunch or sleep because the node is being killed during these hours and something goes awry?

Fear no more! Time intervals can now be blacklisted and/or whitelisted.

```
./estafette-gke-preemptible-killer --blacklist-hours="12:00 - 13:00" --whitelist-hours="09:00 - 17:00"
```

### CODE REVIEW

**Comment by etiennetremel** [comment]
Hi @andrei-pavel, thanks for your contribution. Do you mind updating instructions from the README.md with the new flags and add unit testing on the new introduced functions: processHours, mergeTimespans and updateWhitelistSecondCount?

**Comment by tjespers** [comment]
@etiennetremel @andrei-pavel is there something that has to be done still in order to get this merged? We would love to start using this feature to prevent disruptions during our peak hours! 😄

**Comment by andrei-pavel** [comment]
Hadn't really tested it at all at first, and while writing unit tests the realization came that this didn't work because of some missing boilerplate code and a few functional anomalies.

Thank you for presenting interest! This urges me to finish it until the end of the week. Maybe sooner.

**Comment by andrei-pavel** [comment]
Done! 🎉

#### This works by:
1. projecting creation date and blacklist/whitelist hours between `2000-01-01T00:00:00Z` and `2000-01-02T23:58:00Z` which are arbitrarily chosen years/months/days and are subject to change
2. counting the aggregated duration time resulted from resolving blacklist & whitelist hours
3. replaying that duration time chronologically in sparse intervals in (so called) real-time-realm determined by blacklist & whitelist hours

#### Acknowledgements, disclaimers or limitations:
- Providing no whitelist results in an implicit 47h58m whitelist covering the entire interval specified in point 1 above so that you may specify only blacklists if you wish
- Creation point + drain timeout + randomly generated duration must not exceed 47h58m from 00:00 of starting day; if it needs to reach 47h59m58s, I can do that with minimal changes; if it needs to go beyond that, more significant changes will be required
- Blacklists take precedence over whitelists. This means `-w '05:00 - 08:00' -b '06:00 - 07:00' results in a two-hour time frame instead of the alternative three. This is by chance and can be inverted, but do realize that the same intervals can be created with both methods.
- Hours are specified in 24-hour format.
- Uses https://github.com/google/go-intervals which has seen no activity since November 2017. There is no viable fork that is kept up to date.
- Added unit tests for all functions except `getExpiryDate()` which is partially tested in `main_test.go`
- Haven't tested it on real or dummy Kubernetes deployments as I have little practical experience with them, but @sadym is able and might be willing to

**Comment by andrei-pavel** [comment]
For anyone who wants to test:
```
go get -u github.com/andrei-pavel/estafette-gke-preemptible-killer
estafette-gke-preemptible-killer --help
estafette-gke-preemptible-killer --blacklist-hours '13:00 - 14:00, 16:00 - 17:00' --whitelist-hours '09:00 - 18:00'
```
You need a pretty late version of Go that supports modules with vendors, you'll know you have the wrong one if it can't find `kubernetes/api/v1`.

**Comment by etiennetremel** [comment]
Great job @andrei-pavel thanks a lot!

**Comment by JorritSalverda** [comment]
Sorry, that I'm late to this PR. I didn't document in the readme that you should run `go mod proxy` before pushing changes, but will add this. I've already vendored the `github.com/google/go-intervals` module and the built image is now available as `estafette/estafette-gke-preemptible-killer:1.1.15`.

**Comment by andrei-pavel** [comment]
Blacklists didn't work as they should, because of the implicit 47h58m whitelist interval that I wrote about in a previous comment which is too permissive. I reduced this interval to a 24h interval to fix this bug while reducing code complexity and getting rid of the limitation which is also written in a previous comment `Creation point + drain timeout + randomly generated duration must not exceed 47h58m`. They can now be whatever and they will be whitelisted correctly.

* Also addressed some lint warnings in whitelist.go
* Also relaxed the way hours are parsed, any number of spaces can be placed wherever instead of the more strict `01:00 - 02:00, 03:00 - 04:00` format.

Could you reopen this pull request? Alternatively, I can do another.

**Pull request merged**
