### PR TITLE
evict pods from nodes instead of direct deletion + more!

### PR DESCRIPTION
**Pull request by jbornemann**
Thanks for this tool! We have made a few changes, based on some improvements that have been suggested.

- evict pods from nodes instead of direct deletion #22 
- node deletion time improvements #17

### CODE REVIEW

**Comment by ThommyH** [comment]
Any updates here?

**Comment by jbornemann** [comment]
@JorritSalverda FYI

**Comment by cre8ivejp** [comment]
@jbornemann thanks for replying.
To sad to hear that.
Have you tested your it on production?

**Comment by jbornemann** [comment]
Yes, we have been using it in production successfully

**Comment by cre8ivejp** [comment]
@jbornemann, just to let you know, it's working in production here with no issues. Thank you very much for your contribution to this! I hope they merge this PR soon.

**Review by JorritSalverda — APPROVED** [review]

**Comment by JorritSalverda** [comment]
Sorry about the slow response, have been off for a while. We also no longer run this controller ourselves making verify it's proper working harder. But given that multiple people have confirmed it to work I'll merge and release as version `1.3.0`.

**Pull request merged**
