### PR TITLE
Allow using Workload Identity with helm chart

### PR DESCRIPTION
**Pull request by calind**

### CODE REVIEW

**Comment by JorritSalverda** [comment]
Fixes #71

**Comment by JorritSalverda** [comment]
Thanks for issuing this PR. I've created an issue and milestone in order to be able to create a release (and release notes). Can you update your branch with the base branch, I'll be able to merge the PR once that's done. Unfortunately we have no build status yet for PRs created from forks, so the expected check will never run. I'll merge regardless, since the changes look okay.

**Comment by jtyers** [comment]
@JorritSalverda could you merge? Really keen to be able to deploy this

**Comment by JorritSalverda** [comment]
Yes, quickly looking at how I can assign issue #71 to your name so you get credits for it in the release notes :)

**Comment by cagataygurturk** [comment]
Could you please upload this to the chart repo?

**Comment by JorritSalverda** [comment]
Sorry, it's released now as version 1.2.6.

**Pull request merged**
