### PR TITLE
[✅ TEST] add system test script

### PR DESCRIPTION
**Pull request by andrei-pavel**
This script was extremely useful for me. It allowed me to inspect the results of the killer and thus discover bugs that I couldn't have foreseen and place into unit tests.

Just wanted to share. Feel free to do whatever you want with it.

It starts a kind cluster with the YAML found in the quick start guide, sets the nodes up for preemptible killing, runs the killer, then displays CreationTimestamp and killer annotation.

Tested on Linux. Warning! Might unintentionally delete some clusters.

### CODE REVIEW

**Comment by etiennetremel** [comment]
Looking good. Would it be possible to add a short section in the README.md which explain how to use these scripts?

**Comment by andrei-pavel** [comment]
Will do, totally forgot about that. Describing here now and in the `README.md` later and comments in the script. Basically you give it the arguments that you would have given to the killer which should also be the arguments which you want to test. For instance I ran it with `./test -w '12:00 - 13:00'`. Prerequisites are `docker`, `kind`, `kubectl`. Also `grep`, `sed`, `timeout` to name some that are usually already installed.

**Comment by andrei-pavel** [comment]
Done, renamed the script, placed into scripts directory, made less intrusive, added comments, explained how to run in README.md, even crammed a `.gitignore` update.

Shamelessly do tell whatever minor thing needs to be changed further.

Thank you! 🙏

**Comment by etiennetremel** [comment]
Awesome, thank you @andrei-pavel for your prompt reply contribution!

**Pull request merged**
