### PR TITLE
Add service account to Helm chart

### PR DESCRIPTION
**Pull request by etiennetremel**
close https://github.com/estafette/estafette-gke-preemptible-killer/issues/10

### CODE REVIEW

**Comment by theallseingeye** [comment]
You're missing the mount

```
        volumeMounts:
        - name: app-secrets
          mountPath: /etc/app-secrets
      volumes:
      - name: app-secrets
        secret:
          secretName: {{ template "fullname" . }}
```

**Comment by etiennetremel** [comment]
Oops, good catch 👍 
I added the missing part, as you noticed I wasn't able to test my self, apart of the missing volume mount, was it working as expected?

**Comment by theallseingeye** [comment]
Everything works except this:

```
gcloud iam service-accounts add-iam-policy-binding $service_account_email \
    --member=serviceAccount:${service_account_email} \
     --role=projects/${project_id}/roles/preemptible_killer
```

I had to add it through the web console

**Comment by theallseingeye** [comment]
Maybe too early to say, it says node deleted now. But the node still exists in gcloud, will wait for 24 hours

**Comment by theallseingeye** [comment]
My logs are now like this:

```
{"time":"2019-02-26T10:45:45Z","severity":"info","app":"estafette-gke-preemptible-killer","version":"1.0.35","host":"gke-platform-preemptible-pool-1-0edd4f5c-1bbw","message":"899 minute(s) to go before kill, keeping node"}
{"time":"2019-02-26T10:45:45Z","severity":"info","app":"estafette-gke-preemptible-killer","version":"1.0.35","host":"gke-platform-preemptible-pool-1-0edd4f5c-bq51","message":"Node expired -120 minute(s) ago, deleting..."}
{"time":"2019-02-26T10:45:45Z","severity":"info","app":"estafette-gke-preemptible-killer","version":"1.0.35","host":"gke-platform-preemptible-pool-1-0edd4f5c-bq51","message":"0 pod(s) found"}
{"time":"2019-02-26T10:45:45Z","severity":"info","app":"estafette-gke-preemptible-killer","version":"1.0.35","host":"gke-platform-preemptible-pool-1-0edd4f5c-bq51","message":"Done draining node"}
{"time":"2019-02-26T10:45:47Z","severity":"info","app":"estafette-gke-preemptible-killer","version":"1.0.35","host":"gke-platform-preemptible-pool-1-0edd4f5c-bq51","message":"Node deleted"}
{"time":"2019-02-26T10:45:47Z","severity":"info","app":"estafette-gke-preemptible-killer","version":"1.0.35","host":"gke-platform-preemptible-pool-1-0edd4f5c-c7b0","message":"156 minute(s) to go before kill, keeping node"}
```

But the nodes still exist in gce and are still listed in `kubectl get nodes` just the node is no longer schedulable

**Comment by etiennetremel** [comment]
I just tested on GKE, the node is correctly deleted after binding the appropriate role to the service account. From the gcloud cli instructions I provided, the command was wrong. It has to be done at the project level. I just updated the README.md.

**Pull request merged**
